// Code generated by sqlc. DO NOT EDIT.

package services

import (
	"database/sql"
	"fmt"

	"github.com/google/uuid"
)

type ExerciseCategory string

const (
	ExerciseCategoryHIIT             ExerciseCategory = "HIIT"
	ExerciseCategoryStrengthTraining ExerciseCategory = "Strength_Training"
	ExerciseCategoryCardio           ExerciseCategory = "Cardio"
	ExerciseCategoryYoga             ExerciseCategory = "Yoga"
	ExerciseCategoryBalance          ExerciseCategory = "Balance"
	ExerciseCategoryFlexibility      ExerciseCategory = "Flexibility"
	ExerciseCategoryEndurance        ExerciseCategory = "Endurance"
	ExerciseCategoryOther            ExerciseCategory = "Other"
	ExerciseCategoryWarmUp           ExerciseCategory = "Warm_Up"
	ExerciseCategoryCoolDown         ExerciseCategory = "Cool_Down"
)

func (e *ExerciseCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExerciseCategory(s)
	case string:
		*e = ExerciseCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ExerciseCategory: %T", src)
	}
	return nil
}

type WorkoutSplit string

const (
	WorkoutSplitUpperLower  WorkoutSplit = "Upper_Lower"
	WorkoutSplitFullBody    WorkoutSplit = "Full_Body"
	WorkoutSplitPushPullLeg WorkoutSplit = "Push_Pull_Leg"
	WorkoutSplitYoga        WorkoutSplit = "Yoga"
	WorkoutSplitOther       WorkoutSplit = "Other"
)

func (e *WorkoutSplit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkoutSplit(s)
	case string:
		*e = WorkoutSplit(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkoutSplit: %T", src)
	}
	return nil
}

type Exercise struct {
	ID             uuid.UUID        `json:"id"`
	CreatedAt      sql.NullTime     `json:"created_at"`
	UpdatedAt      sql.NullTime     `json:"updated_at"`
	Category       ExerciseCategory `json:"category"`
	Name           string           `json:"name"`
	NumberOfReps   int32            `json:"number_of_reps"`
	NumberOfSets   int32            `json:"number_of_sets"`
	RepetitionUnit sql.NullString   `json:"repetition_unit"`
	PhotoUrl       sql.NullString   `json:"photo_url"`
	VideoUrl       sql.NullString   `json:"video_url"`
}

type ExerciseWorkout struct {
	ID         uuid.UUID    `json:"id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	ExerciseID uuid.UUID    `json:"exercise_id"`
	WorkoutID  uuid.UUID    `json:"workout_id"`
}

type Workout struct {
	ID        uuid.UUID    `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Name      string       `json:"name"`
	Split     WorkoutSplit `json:"split"`
}
