// Code generated by sqlc. DO NOT EDIT.

package services

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEquipment(ctx context.Context, name sql.NullString) (Equipment, error)
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateExerciseEquipment(ctx context.Context, arg CreateExerciseEquipmentParams) (ExerciseEquipment, error)
	CreateExerciseMuscle(ctx context.Context, arg CreateExerciseMuscleParams) (ExerciseMuscle, error)
	CreateExerciseWorkout(ctx context.Context, arg CreateExerciseWorkoutParams) (ExerciseWorkout, error)
	CreateMuscle(ctx context.Context, name string) (Muscle, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	GetEquipment(ctx context.Context) ([]Equipment, error)
	GetEquipmentById(ctx context.Context, id uuid.UUID) (Equipment, error)
	GetExerciseById(ctx context.Context, id uuid.UUID) (Exercise, error)
	GetExerciseEquipmentById(ctx context.Context, id uuid.UUID) (ExerciseEquipment, error)
	GetExerciseMuscleById(ctx context.Context, id uuid.UUID) (ExerciseMuscle, error)
	GetExerciseWorkoutById(ctx context.Context, id uuid.UUID) (ExerciseWorkout, error)
	GetExerciseWorkoutByWorkoutId(ctx context.Context, id uuid.UUID) (GetExerciseWorkoutByWorkoutIdRow, error)
	GetExercises(ctx context.Context) ([]Exercise, error)
	GetMuscleById(ctx context.Context, id uuid.UUID) (Muscle, error)
	GetMuscles(ctx context.Context) ([]Muscle, error)
	GetWorkout(ctx context.Context) ([]Workout, error)
	GetWorkoutById(ctx context.Context, id uuid.UUID) (Workout, error)
	UpdateEquipmentById(ctx context.Context, arg UpdateEquipmentByIdParams) (Equipment, error)
	UpdateExerciseById(ctx context.Context, arg UpdateExerciseByIdParams) (Exercise, error)
	UpdateExerciseEquipmentById(ctx context.Context, arg UpdateExerciseEquipmentByIdParams) (ExerciseEquipment, error)
	UpdateExerciseMuscleById(ctx context.Context, arg UpdateExerciseMuscleByIdParams) (ExerciseMuscle, error)
	UpdateExerciseWorkoutById(ctx context.Context, arg UpdateExerciseWorkoutByIdParams) (ExerciseWorkout, error)
	UpdateMuscleById(ctx context.Context, arg UpdateMuscleByIdParams) (Muscle, error)
	UpdateWorkoutById(ctx context.Context, arg UpdateWorkoutByIdParams) (Workout, error)
}

var _ Querier = (*Queries)(nil)
