// Code generated by sqlc. DO NOT EDIT.

package services

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateExerciseWorkout(ctx context.Context, arg CreateExerciseWorkoutParams) (ExerciseWorkout, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	GetExerciseById(ctx context.Context, id uuid.UUID) (Exercise, error)
	GetExerciseWorkoutById(ctx context.Context, id uuid.UUID) (ExerciseWorkout, error)
	GetExerciseWorkoutByWorkoutId(ctx context.Context, id uuid.UUID) (GetExerciseWorkoutByWorkoutIdRow, error)
	GetExercises(ctx context.Context) ([]Exercise, error)
	GetRandomExerciseWorkout(ctx context.Context) (GetRandomExerciseWorkoutRow, error)
	GetWorkout(ctx context.Context) ([]Workout, error)
	GetWorkoutById(ctx context.Context, id uuid.UUID) (Workout, error)
	UpdateExerciseById(ctx context.Context, arg UpdateExerciseByIdParams) (Exercise, error)
	UpdateExerciseWorkoutById(ctx context.Context, arg UpdateExerciseWorkoutByIdParams) (ExerciseWorkout, error)
	UpdateWorkoutById(ctx context.Context, arg UpdateWorkoutByIdParams) (Workout, error)
}

var _ Querier = (*Queries)(nil)
